server:
  port: 8081

spring:
  application:
    name: cuenta-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mensaje:
  prueba: Configuracion cargada desde Config Server
  
resilience4j:
  circuitbreaker:
    instances:
      movimientoService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 3