server:
  port: 8083

spring:
  application:
    name: transaccion-service

  kafka:
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
      - localhost:49092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka