server:
  port: 8083

spring:
  application:
    name: transaccion-service

  kafka:
    bootstrap-servers:
      - 52.204.246.248:29092
      - 52.204.246.248:39092
      - 52.204.246.248:49092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka