server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/jotar/Documents/DUOC/OCTAVO%20BIMESTRE/BACKEND%20III/S6/spring_cloud/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
